/* Generated By:JavaCC: Do not edit this line. JERCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JERCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 5;
  /** RegularExpression Id. */
  int TIPO_ENT = 9;
  /** RegularExpression Id. */
  int TIPO_DEC = 10;
  /** RegularExpression Id. */
  int TIPO_CAD = 11;
  /** RegularExpression Id. */
  int TIPO_CAR = 12;
  /** RegularExpression Id. */
  int TIPO_MAT = 13;
  /** RegularExpression Id. */
  int TIPO_VEC = 14;
  /** RegularExpression Id. */
  int TIPO_BOO = 15;
  /** RegularExpression Id. */
  int OBT = 16;
  /** RegularExpression Id. */
  int IMP = 17;
  /** RegularExpression Id. */
  int REPETIR = 18;
  /** RegularExpression Id. */
  int MIENTRAS = 19;
  /** RegularExpression Id. */
  int SI = 20;
  /** RegularExpression Id. */
  int SINO = 21;
  /** RegularExpression Id. */
  int FUN = 22;
  /** RegularExpression Id. */
  int EVALUAR = 23;
  /** RegularExpression Id. */
  int CUANDO = 24;
  /** RegularExpression Id. */
  int TERMINAR = 25;
  /** RegularExpression Id. */
  int PRED = 26;
  /** RegularExpression Id. */
  int RET = 27;
  /** RegularExpression Id. */
  int PIN = 28;
  /** RegularExpression Id. */
  int SALIDA = 29;
  /** RegularExpression Id. */
  int ENTRADA = 30;
  /** RegularExpression Id. */
  int ENTRADA_UP = 31;
  /** RegularExpression Id. */
  int ANALOGO = 32;
  /** RegularExpression Id. */
  int PWM = 33;
  /** RegularExpression Id. */
  int ENCENDER = 34;
  /** RegularExpression Id. */
  int APAGAR = 35;
  /** RegularExpression Id. */
  int LEER = 36;
  /** RegularExpression Id. */
  int LEER_A = 37;
  /** RegularExpression Id. */
  int DEBER = 38;
  /** RegularExpression Id. */
  int COMO = 39;
  /** RegularExpression Id. */
  int ESPERAR = 40;
  /** RegularExpression Id. */
  int INICIO = 41;
  /** RegularExpression Id. */
  int BUCLE = 42;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 43;
  /** RegularExpression Id. */
  int NUMERO_DECIMAL = 44;
  /** RegularExpression Id. */
  int CADENA = 45;
  /** RegularExpression Id. */
  int CARACTER = 46;
  /** RegularExpression Id. */
  int VERDADERO = 47;
  /** RegularExpression Id. */
  int FALSO = 48;
  /** RegularExpression Id. */
  int ASIG_INC = 49;
  /** RegularExpression Id. */
  int ASIG_DEC = 50;
  /** RegularExpression Id. */
  int ASIGNACION = 51;
  /** RegularExpression Id. */
  int POTENCIA = 52;
  /** RegularExpression Id. */
  int RAIZ = 53;
  /** RegularExpression Id. */
  int INC = 54;
  /** RegularExpression Id. */
  int DEC = 55;
  /** RegularExpression Id. */
  int SUMA = 56;
  /** RegularExpression Id. */
  int RESTA = 57;
  /** RegularExpression Id. */
  int MULT = 58;
  /** RegularExpression Id. */
  int DIV = 59;
  /** RegularExpression Id. */
  int MODULO = 60;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 61;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 62;
  /** RegularExpression Id. */
  int DIFERENTE = 63;
  /** RegularExpression Id. */
  int IGUAL = 64;
  /** RegularExpression Id. */
  int MAYOR_QUE = 65;
  /** RegularExpression Id. */
  int MENOR_QUE = 66;
  /** RegularExpression Id. */
  int AND = 67;
  /** RegularExpression Id. */
  int OR = 68;
  /** RegularExpression Id. */
  int NOT = 69;
  /** RegularExpression Id. */
  int APERTURA_PAREN = 70;
  /** RegularExpression Id. */
  int CIERRE_PAREN = 71;
  /** RegularExpression Id. */
  int APERTURA_BLOQUE = 72;
  /** RegularExpression Id. */
  int CIERRE_BLOQUE = 73;
  /** RegularExpression Id. */
  int APERTURA_CORCHETE = 74;
  /** RegularExpression Id. */
  int CIERRE_CORCHETE = 75;
  /** RegularExpression Id. */
  int FIN_INSTRUCCION = 76;
  /** RegularExpression Id. */
  int SEPARADOR = 77;
  /** RegularExpression Id. */
  int PUNTO = 78;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 79;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ESTADO_COMENTARIO = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMENTARIO_LINEA>",
    "\"/**\"",
    "\"**/\"",
    "<token of kind 8>",
    "\"ENT\"",
    "\"DEC\"",
    "\"CAD\"",
    "\"CAR\"",
    "\"MAT\"",
    "\"VEC\"",
    "\"BOO\"",
    "\"OBT\"",
    "\"IMP\"",
    "\"REPETIR\"",
    "\"MIENTRAS\"",
    "\"SI\"",
    "\"SINO\"",
    "\"FUN\"",
    "\"EVALUAR\"",
    "\"CUANDO\"",
    "\"TERMINAR\"",
    "\"PRED\"",
    "\"RET\"",
    "\"PIN\"",
    "\"SALIDA\"",
    "\"ENTRADA\"",
    "\"ENTRADA_UP\"",
    "\"ANALOGO\"",
    "\"PWM\"",
    "\"ENCENDER\"",
    "\"APAGAR\"",
    "\"LEER\"",
    "\"LEER_A\"",
    "\"DEBER\"",
    "\"COMO\"",
    "\"ESPERAR\"",
    "\"INICIO\"",
    "\"BUCLE\"",
    "<NUMERO_ENTERO>",
    "<NUMERO_DECIMAL>",
    "<CADENA>",
    "<CARACTER>",
    "\"VERDADERO\"",
    "\"FALSO\"",
    "\"+->\"",
    "\"-->\"",
    "\"->\"",
    "\"**\"",
    "\"//\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFICADOR>",
  };

}
